# Generated by Django 5.2.7 on 2026-03-12 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0003_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='event_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
