# Generated by Django 5.2.7 on 2026-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0004_alter_event_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Archived', 'Archived')], db_index=True, default='Pending', max_length=20),
        ),
    ]
