# Generated by Django 5.2.7 on 2026-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='funds_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
