# Generated by Django 5.1.6 on 2026-04-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='group',
            name='invited_users',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupjoinrequest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupjoinrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupjoinrequest',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupJoinRequest',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
