# Generated by Django 5.1.6 on 2026-05-21 04:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chipin', '0008_remove_event_group_remove_event_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('fuel_consumption', models.DecimalField(decimal_places=1, max_digits=7)),
                ('fuel_unit', models.CharField(choices=[('L/hr', 'L/hr'), ('gal/hr', 'gal/hr')], default='L/hr', max_length=10)),
                ('speed_unit', models.CharField(choices=[('kts', 'kts'), ('km/h', 'km/h')], default='kts', max_length=10)),
                ('vso', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vs1', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vx', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vy', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vfe', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vno', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vne', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('va', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vlo', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vle', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
    ]
