# Generated by Django 5.1.6 on 2026-05-27 07:08

import chipin.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('checklist', 'Checklist'), ('maintenance', 'Maintenance Release'), ('manual', 'Manual')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=chipin.models.aircraft_document_upload_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chipin.aircraft')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
