# Generated by Django 5.1.6 on 2026-06-03 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0010_aircraftdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pretakeoff', 'Pre-Takeoff'), ('inflight', 'In Flight'), ('complete', 'Complete')], default='pretakeoff', max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('aircraft_free', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('start_fuel', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('fuel_unit', models.CharField(blank=True, default='L', max_length=10)),
                ('departure', models.CharField(blank=True, max_length=150)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('vdo_start', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('airswitch_start', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('pilot_in_command', models.CharField(blank=True, max_length=150)),
                ('additional_crew', models.JSONField(blank=True, default=list)),
                ('passenger_count', models.IntegerField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('end_fuel', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('actual_destination', models.CharField(blank=True, max_length=150)),
                ('vdo_end', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('airswitch_end', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chipin.aircraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='chipin.flightrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
