# Generated by Django 5.1.6 on 2026-06-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0011_flightrecord_flightannotation_location_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrecord',
            name='scheduled_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightrecord',
            name='scheduled_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
