# Generated by Django 5.1.6 on 2026-06-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0012_flightrecord_scheduled_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrecord',
            name='scheduled_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightrecord',
            name='scheduled_departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
