# Generated by Django 5.1.6 on 2026-06-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0013_alter_flightrecord_scheduled_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrecord',
            name='fuel_added',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
    ]
