# Generated by Django 5.1.6 on 2026-06-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0014_flightrecord_fuel_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='max_fuel',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
    ]
