# Generated by Django 5.1.6 on 2026-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0015_aircraft_max_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='fuel_unit',
            field=models.CharField(choices=[('L/hr', 'L/hr')], default='L/hr', max_length=10),
        ),
    ]
