# Generated by Django 5.2.7 on 2026-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_max_spend_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_spend',
            field=models.DecimalField(decimal_places=5, default=100.0, max_digits=10),
        ),
    ]
