# Generated by Django 5.2.7 on 2026-03-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transaction_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
