# Generated by Django 5.1.6 on 2026-04-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
